version: '3.9'

services:
  db:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: docker/web
    ports:
      - 8080:80
    volumes:
      - .:/var/www
    depends_on:
      - db

volumes:
  db:
    driver: local
